version: "3"	#docker version 3 사용
services: 	#service들 정의
  database: 	#service 이름
    image: mysql	#불러올 image
    container_name: user-service-db	#container 이름 지정
    environment:	# 환경 설정
      - MYSQL_DATABASE=user-service
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    ports:		#port 지정
      - 3306:3306
    volumes:	#볼륨 지정
      - ./db/data:/var/lib/mysql


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "22181:2181"


  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
       - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CREATE_TOPICS: "my-topic"   # Topic명:Partition개수:Replica개수
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


#networks:	#네트워크 설정
#  starbucks_network_02: