#version: "3"
#
#services:
#  master-server:
#    image: mysql:8.0
#    container_name: mysql-master
#    restart: always
#    ports:
#      - 3306:3306
#    volumes:
#      - ./db/conf.d:/etc/mysql/conf.d
#      - ./db/data:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=1234
#      - TZ=Asia/Seoul`

version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
