spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: user-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.35.145.182/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info